### ISSUE TITLE
Kubernetes admissionreview lacks autocomplete description

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#215]
**Describe the bug**

**To Reproduce**
1. Run `cnquery shell k8s`
2. Type `k8s.` and tag to get the autocomplete

**Expected behavior**
admissionreview should have a description

**Screenshots**
<img width="625" alt="image" src="https://user-images.githubusercontent.com/1015200/194646858-8233d679-b811-43ab-9ab0-22dc2754507c.png">

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by arlimus** [comment]
I'm curious to understand why this was re-opened:

The bug is gone for `k8s.admissionreview` which is fixed. 

![image](https://user-images.githubusercontent.com/1307529/196762335-f07cbee6-743c-4404-9175-3e31d1aa8d15.png)

It also works for `k8s.pods`:

![image](https://user-images.githubusercontent.com/1307529/196762405-a50feb00-86fa-46ca-9d2d-f5cd7558a01f.png)

Now for `k8s.pod` and `k8s.kubelet` and any other resource that looks like it: The problem is not with the autocomplete, but with the way the resource is written. Right now, given the LR definitions, it says: "users need to fill in all the fields, because it cannot be automatically initialized". However, that is not true, looking at how the resources function. They do an amazing auto-initialization! However, the shell nor users cannot know that. Once we fix that, it will show up in auto-complete.

+1 on rbac, let's get it documented.

For all other cases, where we have a named init, I think we'll still want to show it in auto-complete later on, but we also want to show how the arguments work that it requires. Same as calling resources, that don't have an init and require arguments.
