### ISSUE TITLE
handle provider shutdown in a way that doesn't kill other invocations

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnquery#2509]
in ephemeral environments where we end up with many invocations running in parallel, the shutdown can cause a shutdown of another job. in these ephemeral envs, there's no real need for the shutdown because memory is released when the invocation is done doing its thing

**Comment by imilchev** [comment]
Adding an env var to disable provider shutdown sounds like a workaround instead of a fix. Also IIRC some providers execute logic on shutdown. We may run into problems if we never shut them down.

To fix this we should move this line https://github.com/mondoohq/cnquery/blob/main/explorer/scan/local_scanner.go#L180 out of the job. The coordinator shutdown was used as a shortcut to shutdown all providers. However, we encounter the issue that you mention for AWS and for scan API, where multiple scans can happen in parallel.

I feel like the proper fix for this should be to move the coordinator shutdown to the command (somewhere here https://github.com/mondoohq/cnquery/blob/main/apps/cnquery/cmd/scan.go#L128). Instead of it, inside the scan job we should just shutdown the providers/runtimes that we created there **explicitly**. In this way one job cannot close the providers for another.

If we go down that road we should be able to tackle both the AWS issue and the scan API issue with 1 fix

**Comment by vjeffrey** [comment]
for the ephemeral env i was talking about we're actually going to use the builtin provider to circumvent the need to download the providers in the first place, which should also eliminate this problem in that case
