### ISSUE TITLE
AWS provider without a region throws errors

### ISSUE THREAD

**Issue by arlimus** [mondoohq/cnquery#539]
**Describe the bug**

When using AWS but without specifying a region, I get a ton of errors:

![image](https://user-images.githubusercontent.com/1307529/205215925-64301d02-e690-4008-9503-aed16ffbdac8.png)

**Expected behavior**

For commands like `aws.ec2.instances` I'd love to reduce the errors that we throw in this case. I still think it's helpful to notify users if we can't access certain regions, but be more specific about and avoid the duplication. 

For commands like `aws.account` I wonder if we can work around the error. If I specify a working region beforehand, I can read out the account info. 

Additionally, it would be great if users could specify the region. I'm not sure if we'd want a `region` subcommand or a `--region` arg...

**Comment by vjeffrey** [comment]
you specify the region with a flag or env var:
<img width="1437" alt="Screenshot 2022-12-02 at 11 18 15" src="https://user-images.githubusercontent.com/10341541/205359583-72c8cf36-9cc6-440f-a69a-0dce54b5efcf.png">



the error is because the aws credentials always require a region to be specified (you'd see the same err if you tried to access the aws api). we can default to us-east-1 if no region is specified, ill work on that 👍
